### ISSUE TITLE
Installing CGL fails on MacOS

### ISSUE THREAD

**Issue by dirkschumacher** [coin-or-tools/homebrew-coinor#59]
It might to be the same problem as with `clp` where `osi` needs to be an explicit dependency.

```
Installing cgl from coin-or-tools/coinor
==> Downloading https://www.coin-or.org/download/pkgsource/Cgl/Cgl-0.60.2.tgz
Already downloaded: /Users/dirkschumacher/Library/Caches/Homebrew/downloads/441bdec2fa922a7323e44dc52cd12cd4fa592b0b4651461adffc6408380f5ff7--Cgl-0.60.2.tgz
==> ./configure --prefix=/usr/local/Cellar/cgl/0.60.2 --datadir=/usr/local/Cellar/cgl/0.60.2/share/cgl --includedir=/usr/local/Cellar/cgl/0.60.2/inclu
Last 15 lines from /Users/dirkschumacher/Library/Logs/Homebrew/cgl/01.configure:
checking for gfortran option to produce PIC... -fno-common
checking if gfortran PIC flag -fno-common works... yes
checking if gfortran static flag -static works... no
checking if gfortran supports -c -o file.o... yes
checking whether the gfortran linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin18.7.0 dyld
checking how to hardcode library paths into programs... immediate
configure: Build is "i386-apple-darwin18.7.0".
configure: Applying patches to libtool for Darwin
checking if library version is set... 11:2:10
checking for pkg-config... pkg-config
checking pkg-config is at least version 0.16.0... yes
checking for COIN-OR package CoinUtils... yes: 2.11.2 
checking for COIN-OR package Osi... not given: No package 'osi' found
configure: error: Required package Osi not available.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/coin-or-tools/homebrew-coinor/issues
```

**Comment by tkralphs** [comment]
The explicit dependency on `osi` shouldn't be needed since `clp` depends on `osi`. What seems to be happening is that someone just got a recipe for Clp into homebrew core (https://github.com/Homebrew/homebrew-core/blob/master/Formula/clp.rb), which does not depend on `osi`. This recipe has a bottle and the bottle gets installed, but then osi is missing. 

A solution (for now) is to make the dependencies on formulas in this tap explicit, which I just did 
 in 54bf5880dd15fb022eaffdc0cd7947544e468f0b. The main issue I see with this is that you'll get an error if you try to install, e.g., cgl when you already have clp installed from core. It tells you what to do to fix the error, so I guess it's not a big hurdle. @dpo what do you think? We could rename the recipes, but I like keeping them with the same names. We could also try to get `osi` in as a dependency in core. I guess someone may eventually want `cbc` there and then it will be necessary.

**Comment by dirkschumacher** [comment]
@tkralphs thanks. However 54bf588 introduces a bug which prevents installation as far as I see it as there is a typo: `coin-or-tool` => `coin-or-tools`
