### ISSUE TITLE
Updating formulas with new versions of packages

### ISSUE THREAD

**Issue by Alexander-Belyi** [coin-or-tools/homebrew-coinor#70]
Continuing the discussion from #62.
I've found what was the problem with Cbc: in 2.10.6, unit tests started using miplib3, and it wasn't installed. When I add the dependency and the flag `--with-miplib3-datadir`, everything installs.
There're a few other things:
1. Should the links from coin_data_*.rb be updated? Currently, they point to https://www.coin-or.org/download.
2. Should the case when `--with-miplib3-datadir` is not provided be better handled? Probably worth opening another issue in Cbc, unless it is ensured never to happen.
3. Building `--with-glpk` doesn't work from `homebrew`, while working from `coinbrew`:
I'm getting `configure: error: Cannot find file amd.h in /private/tmp/clp-20220119-30586-1qyaz5p/Clp-releases-1.17.7/Clp`

**Comment by tkralphs** [comment]
First, yes, the recipes for coin_data_* should definitely be updated, too. I had that on my TODO list. The new download URLs should point to the coin-or-tools/Data-*. 

The case when MIPLIB3 is not provided does actually seem to be handled properly---it's optional and the part of the unit test that depends on it only runs when it's present. The configure script has a check for this and the argument only gets added to the unit test if it's present. That seems to be what happened. In general, we don't want to run this part of the unit test for an install, since it takes a long time. 

That part of the unit test that is _not_ intended to be optional is `coin_data_sample`. The real mystery seems to be why its presence was not detected as it seems it should have been, since `coin_data_sample` is a dependency of CoinUtils and thus should be installed no matter what. Can you check whether you have `coin-data_sample`. If not, try re-installing CoinUtils and see if it pulls it in, as it should. If you do have, then rebuild Cbc and see if configure detects its presence or just do `pkg-config --exists coin_data_sample`.

For the Glpk error, could you open another issue?

**Comment by Alexander-Belyi** [comment]
> That part of the unit test that is _not_ intended to be optional is `coin_data_sample`. 

From my understanding of the code, it is not the case. Please, look at [this commit](https://github.com/coin-or/Cbc/commit/ead9585e7f8b9934337ae98f245d2370dbdab55e#diff-fb83f98b27f62e3c3ed1e8605819201b6002c7e0e1fed0718de90d065afaf754). I'm not sure how exactly `Makefile.am` and `Makefile.in` are used to create the `Makefile`, but in any case, from `Makefile.am` only  ```cbcflags += -dirMiplib `$(CYGPATH_W) $(MIPLIB3_DATA)` -unitTest``` can be executed, and in `Makefile.in`, `cbcflags` is defined as ```cbcflags = $(am__append_4)```, and ```@COIN_HAS_MIPLIB3_TRUE@am__append_4 = -dirMiplib `$(CYGPATH_W) $(MIPLIB3_DATA)` -unitTest```. All the lines that involve `SAMPLE_DATA` are commented out.
And that what happens when building using `coinbrew` too: only miplib3 unit tests are run.

> The case when MIPLIB3 is not provided does actually seem to be handled properly

Well, in the case when `COIN_HAS_MIPLIB3` is false `cbcflags` stays empty, so the Cbc executable runs without any parameters and blocks the build. In the case when MIPLIB3 is not provided, Cbc shouldn't be run at all.

**Comment by tkralphs** [comment]
@Alexander-Belyi Oh yeah, I see what you're saying now. I actually looked right at that commit when I was poking at this earlier and completely missed the `#` on the line with the flags for the sample data. It was never caught in our testing because MIPLIB3 _is_ a dependency of the project when it's checked out from source. 

It _is_ true that the only part of the unit test not _intended_ to be optional is `coin_data_sample` and I think configuration will fail if it's not present, so once this bug is fixed, there should be no need to handle the case when neither MIPLIB3 or the sample data are installed. I guess the reason why everything was fine for the others who tested it is because they had MIPLIB3 installed already. I guess I'll need to make a new release to fix this, since otherwise, it will surely break for others, too. Thanks for debugging this!

**Comment by Alexander-Belyi** [comment]
Ok, great we are on the same page now. So, with Cbc, should we keep its formula as it is for now until you release a new version, or should I add miplib3 as a dependency?

> First, yes, the recipes for coin_data_* should definitely be updated, too.

Ok, and what about other formulas not related to Cbc (vol, dylp, symphony)? I haven't tried installing them, but I guess I can try and update them as well.

**Comment by tkralphs** [comment]
> So, with Cbc, should we keep its formula as it is for now until you release a new version, or should I add miplib3 as a dependency?

I guess the argument for not making miplib3 a dependency is that it makes the unit test take longer to run and without any real purpose. The idea of the tests that use sample was just to be a quick check that everything is installed correctly. So I guess I wouldn't. In fact, I'm thinking now that the miplib3 test shouldn't be run by default, even when miplib3 is present. We can create a separate target for that, which is the way I have it in SYMPHONY. 

> what about other formulas not related to Cbc (vol, dylp, symphony)?

I just made a new release of SYMPHONY and it would be great if you could update that one. vol and dylp haven't had a new release since we moved to Github, but I do plan on making one in the relatively near future, so you can hold off on those.

**Comment by tkralphs** [comment]
I now made a new release of Cbc to fix the problem with the unit test and updated to the latest releases using linuxbrew (see #71). I'm going to close this issue.

**Comment by Alexander-Belyi** [comment]
Thanks, now it works. I've submitted a pull request with updated `coin_data_*.rb` files. I still have problems with the `--with-glpk` flag and also the new version of Symphony. I'll create new issues for these.
